# Generated by Django 2.2.3 on 2019-07-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=100)),
                ('user_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfferAppApi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfferAppApi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='date published')),
                ('order_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfferAppApi.Store')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfferAppApi.User')),
            ],
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_text', models.CharField(max_length=200)),
                ('store_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfferAppApi.Store')),
            ],
        ),
    ]
